#!/bin/bash
#Our comment is here
test -e ./results.txt && rm -f ./results.txt
javac PageNumber.java
while read LINE
do java PageNumber "$LINE" >> results.txt
done < ./initValuesPages.txt
rm -f ./*.class