#!/bin/bash
javac -d ./test/java/ ./main/java/Towns.java
cd ./test/java
javac -cp .:"junit-4.12.jar" TownsTests.java
var=$(java -cp .:"junit-4.12.jar:hamcrest-core-1.3.jar" org.junit.runner.JUnitCore TownsTests)
if [[ $var == *"OK (1 test)"* ]]
then
echo "$var" > output.txt
fi
rm -f ./*.class