#!/bin/bash
javac -d ./test/java/ ./main/java/Towns.java
cd ./test/java
javac -cp .:"junit-4.12.jar" TownsTests.java
java -cp .:"junit-4.12.jar:hamcrest-core-1.3.jar" org.junit.runner.JUnitCore TownsTests > ./output.txt
rm -f ./*.class