#!/bin/bash
#Our comment is here
test -e ./results.txt && rm -f ./results.txt
javac NumberRandom.java
while read LINE
do java NumberRandom "$LINE" >> results.txt
done < ./initValuesRandom.txt
rm -f ./*.class